### ISSUE TITLE
[ IMPROVEMENT ] : The tittle color can be changed in banner as this is not cleary visible due to same background color 

### ISSUE THREAD

**Issue by rohan-kulkarni-25** [SurPathHub/hacktoberfest-philippines#17]
![Screenshot from 2021-09-18 09-48-52](https://user-images.githubusercontent.com/76584243/133872246-de03f634-8e58-4753-b187-370472dc74fd.png)

**Comment by Tiansing** [comment]
@rohan-kulkarni-25 Do you want to take this issue?

**Comment by rohan-kulkarni-25** [comment]
No, I will be happy to work but let any beginner take it they will get
green squares

**Comment by jcavenue** [comment]
I will fix these issues later

**Comment by jcavenue** [comment]
Done
