### ISSUE TITLE
Change the background

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/hacktoberfest-philippines#19]
For me. the recent background is much better than this 👇 

![image](https://user-images.githubusercontent.com/73097560/133879912-22edf326-c057-4c8e-9be4-39c1bcc89f17.png)

**Comment by jcavenue** [comment]
it's from @Tiansing

**Comment by vinzvinci** [comment]
![image](https://user-images.githubusercontent.com/73097560/133880197-dff5df12-09ba-4be7-a0c1-a6d3dd943552.png)

I like the background color here

**Comment by jcavenue** [comment]
Replace.

**Comment by Tiansing** [comment]
> ![image](https://user-images.githubusercontent.com/73097560/133880197-dff5df12-09ba-4be7-a0c1-a6d3dd943552.png)
> 
> I like the background color here

ok ill send the revised design to @jcavenue

**Comment by vinzvinci** [comment]
All good @Tiansing 🚀
