### ISSUE TITLE
Add Pack & Discord section

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/hacktoberfest-philippines#22]
Can you add this section?

![image](https://user-images.githubusercontent.com/73097560/134274240-874d5174-a504-485f-aa4e-9101f5ec23aa.png)

Here's the priority link for the student developer pack:
https://education.github.com/discount_requests/student_application?utm_source=2021-10-03-HacktoberfestPhilippines

That link will work on October 3

:link: Discord Community Invite link: https://discord.com/invite/RATJsSGM9d

**Comment by vinzvinci** [comment]
The designs will be up to you lods @jcavenue

**Comment by jcavenue** [comment]
Issue fix
