### ISSUE TITLE
Repositories to add and remove

### ISSUE THREAD

**Issue by vinzvinci** [SurPathHub/hacktoberfest-philippines#25]
Hi @jcavenue, please add and remove those suggestions below 

### Add
- https://github.com/SurPathHub/starter-kit
  - Maintainer: @vinzvinci @nikxherrera
- https://github.com/SurPathHub/brand-assets
  - Maintainer: @jcavenue @vinzvinci @nikxherrera

### Remove
- Field Day 
  - We can't make our own website for Field Day I think because we will use https://githubfieldday.com/
  
Here 👇 
![image](https://user-images.githubusercontent.com/73097560/134787950-8af1ef71-3449-48ab-ac6c-8c3d21de2072.png)

**Comment by jcavenue** [comment]
Okay, I will add it on my backlogs

**Comment by vinzvinci** [comment]
Update this. Hacktoberfest will start tomorrow.

**Comment by vinzvinci** [comment]
I decided to do this https://github.com/SurPathHub/hacktoberfest-philippines/commit/c20e126dc5c44a3769293caaa14de8c50c946e70
